<?php
/**
 * Created by PhpStorm.
 * User: inhere
 * Date: 2017-08-24
 * Time: 17:42
 */

namespace App\Cli;

use inhere\library\di\Container;

/**
 * Class App
 * @package App\Cli
 */
class App extends \inhere\console\App
{
    /**
     * @var Container
     */
    private $di;

    protected function init()
    {
        \Sws::$app = $this;

        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @param Container $di
     */
    public function setDi($di)
    {
        $this->di = $di;
    }

    /**
     * @return Container
     */
    public function getDi()
    {
        return $this->di;
    }
}