<?php
/**
 * Created by PhpStorm.
 * User: inhere
 * Date: 2017-08-24
 * Time: 17:42
 */

namespace App\Console;

use inhere\console\App;
use Sws\ApplicationInterface;
use Sws\ApplicationTrait;

/**
 * Class Application
 * @package App\Console
 */
class Application extends App implements ApplicationInterface
{
    use ApplicationTrait;

    protected function init()
    {
        \Sws::$app = $this;

        parent::init(); // TODO: Change the autogenerated stub
    }
}
